// nuxt-3-template/pages/home/-components/home-top-bar.vue
<template>
  <nav
    class="flex flex-row items-center justify-between w-full"
    style="user-select: none"
  >
    <nuxt-link to="/settings">
      <iconify-icon width="28" icon="mdi:cog"></iconify-icon>
    </nuxt-link>
    <nuxt-link to="/">
      <h1 class="page-title logo text">GBreath</h1>
    </nuxt-link>
    <client-only>
      <div>
        <iconify-icon
          v-if="$colorMode.value === 'dark'"
          width="28"
          icon="ph:sun-fill"
          @click="$colorMode.preference = 'light'"
        ></iconify-icon>
        <iconify-icon
          v-if="$colorMode.value === 'light'"
          width="28"
          icon="ph:moon-fill"
          @click="$colorMode.preference = 'dark'"
        ></iconify-icon>
      </div>
    </client-only>
  </nav>
</template>

// src/routes/Home/components/HomeTopbar.svelte
<style lang="scss" scoped>
header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 16px;
  h1 {
    font-size: 24px;
    cursor: pointer;
    user-select: none;
  }
  button {
    display: grid;
    place-items: center;
    border: 0;
    background: transparent;
    cursor: pointer;
  }
}
</style>

<script lang="ts">
import { ChangeUserPreference, userPreferences } from "@/utils/userPreferences";

import Icon from "@iconify/svelte";
import { Link, globalHistory } from "svelte-navigator";

let isDark = true;

if (userPreferences.theme === "light") {
  isDark = false;
}

function changeTheme() {
  if (isDark) {
    ChangeUserPreference.theme("light");
    isDark = false;
  } else {
    ChangeUserPreference.theme("dark");
    isDark = true;
  }
}
</script>

<header>
  <Link to="/settings">
    <Icon icon="bx:bxs-cog" />
  </Link>
  <h1 class="logo" on:click="{() => globalHistory.navigate('/')}">GBreath</h1>
  <button on:click="{() => changeTheme()}">
    {#if isDark}
      <Icon icon="bx:bxs-sun" />
    {/if}
    {#if !isDark}
      <Icon icon="bx:bxs-moon" />
    {/if}
  </button>
</header>
