// src/routes/Home/Index.svelte
<style lang="scss" scoped>
.home-content {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 16px;
}
</style>

<script lang="ts">
import BreathingExercisePicker from "./components/BreathingExercisePicker.svelte";
import HomeTopbar from "./components/HomeTopbar.svelte";
import StreakOverview from "./components/StreakOverview.svelte";
</script>

<HomeTopbar />
<div class="home-content">
  <!-- <StreakOverview /> -->
  <BreathingExercisePicker />
</div>

// pages/home/index.vue
<script lang="ts" setup>
import HomeTopBar from "./-components/home-top-bar.vue";
import BreathingExercicePicker from "./-components/breathing-exercice-picker.vue";
import StreakOverview from "./-components/streak-overview.vue";
</script>

<template>
  <main class="page-content items-center justify-center">
    <home-top-bar />
    <streak-overview />
    <breathing-exercice-picker />
  </main>
</template>
